### ISSUE TITLE
American spellings don't work in config file

### ISSUE THREAD

**Issue by brandonchinn178** [NorfairKing/sydtest#75] opened 2023-09-13 18:39 UTC
`randomize-execution-order: false` doesn't seem to work in the config file, but `randomise-execution-order: false` does. Is that expected?

**Comment by brandonchinn178** [comment] 2023-09-13 22:52
I understand why the default is true; in general, I agree that randomizing the test order is good to prevent a implicit dependency on the order of tests.

In my case, all my tests are unit tests and I want the output order to match the order in the source code, to match the spec. It's just aesthetics, so I don't think `sequential` is the right thing here.

**Comment by brandonchinn178** [comment] 2023-09-13 22:53
Also, can you explain why this is expected? I do see this: https://github.com/NorfairKing/sydtest/blob/a3ba5f3096c3dcc58920f61ba8a45191d9020eb4/sydtest/src/Test/Syd/OptParse.hs#L268-L269

And the help text does say it's allowed:
```
# any of
[ randomise-execution-order: # optional
    # Randomise the execution order of the tests in the test suite
    <boolean>
, randomize-execution-order: # optional
    # American spelling
    <boolean>
]
```

**Comment by NorfairKing** [comment] 2023-09-27 08:52
@brandonchinn178 It looks like I made two mistakes in one message:

1. I was supposed to say `doNotRandomiseExecutionOrder` instead of `sequential`.
2. I mistakenly thought the American spelling wasn't supposed to be supported yet.

It also looks like there's an issue with the parsing.
I'm investigating now if it's `autodocodec` that's broken.

**Comment by NorfairKing** [comment] 2023-09-27 10:06
I've added another test to autodocodec and haven't found the issue, but now I think I have an idea what the issue is.

**Comment by NorfairKing** [comment] 2023-09-27 13:34
I figured out why this happened:

https://github.com/NorfairKing/autodocodec/commit/c8d56ace5b4c5b1137d9a8eaac11c64531e9be14#diff-d42217527abcf98c817a6d39cb84537548449dbefe2ce1eb569dcc249a935331R1618-R1627

It turns out that I misunderstood (my own) autodocodec API and caused this bug.
I'll have to revisit the autodocodec API to make this kind of issue solveable.

**Comment by NorfairKing** [comment] 2024-11-01 12:46
This should be fixed now that sydtest uses `opt-env-conf`.

**Closed by NorfairKing** 2024-11-01 12:46 UTC
